name: Deploy to EC2

on:
  push:
    branches:
      - master

env:
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ubuntu
  SSH_HOST: 44.201.214.8

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "cd ~/Desktop/exampleapp && git pull"
