name: Pull and run from EC2

on:
  push:
    branches:
      - master

env:
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ubuntu
  SSH_HOST: ${{ vars.SSH_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.EC2_SSH_KEY }}

      - name: Pull & run from EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} '
          if ! command -v docker &> /dev/null; then
            sudo apt-get update -y &&
            sudo apt-get install -y docker.io
          fi &&
          mkdir -p ~/Desktop/ask_sahil &&
          cd ~/Desktop/ask_sahil && 
          git pull &&
          docker-compose up --build
        '