name: Pull and run from EC2

on:
  push:
    branches:
      - master

env:
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ubuntu
  SSH_HOST: ${{ vars.SSH_HOST }}
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  FOR_AWS_TO_GITHUB: ${{ secrets.FOR_AWS_TO_GITHUB_PVT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.EC2_SSH_KEY }}

      - name: Pull & run from EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} '
          if ! command -v docker &> /dev/null; then
            sudo apt-get update -y &&
            sudo apt-get install -y docker.io
          fi &&
          mkdir -p ~/Desktop/ask_sahil &&
          cd ~/Desktop/ask_sahil && 
          # If github.com is not in known hosts, add it
          if ! ssh-keygen -F "github.com" >/dev/null; then
            # Add the host to known_hosts
            ssh-keyscan -t rsa "$HOST" >> ~/.ssh/known_hosts
          fi
          ssh-keyscan github.com >> ~/.ssh/known_hosts &&  
          git init &&
          echo {{ env.FOR_AWS_TO_GITHUB }} >> ~/.ssh/for_aws_to_github &&
          if [ ! -f ~/.ssh/config ]; then
            # Create the config file and add the configuration for GitHub
            touch ~/.ssh/config
            echo "Host github.com" >> ~/.ssh/config
            echo "  Hostname      github.com" >> ~/.ssh/config
            echo "  User          git" >> ~/.ssh/config
            echo "  IdentityFile  ~/.ssh/for_aws_to_github" >> ~/.ssh/config
            echo "Created ~/.ssh/config and added configuration for github.com"
          else
            # Check if the configuration for GitHub already exists
            if grep -q "^Host github.com" ~/.ssh/config; then
              echo "Configuration for github.com already exists in ~/.ssh/config"
            else
              # Add the configuration for GitHub to the existing config file
              echo "Host github.com" >> ~/.ssh/config
              echo "  Hostname      github.com" >> ~/.ssh/config
              echo "  User          git" >> ~/.ssh/config
              echo "  IdentityFile  ~/.ssh/for_aws_to_github" >> ~/.ssh/config
              echo "Added configuration for github.com to ~/.ssh/config"
            fi
          fi
          git pull git@github.com:bhamshu/ask_sahil.git &&
          export OPENAI_KEY=${{ env.OPENAI_KEY }} && 
          sudo gpasswd -a $USER docker &&
          newgrp docker &&
          docker-compose up --build'
